version: 2.1

jobs:
  test-node:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Navigate to Backend Folder
          command: cd backend
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test --passWithNoTests

workflows:
  version: 2
  test:
    jobs:
      - test-node
