version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Navigate to Backend Folder
          command: cd backend
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build the Project
          command: npm run build
